### ISSUE TITLE
Can not encrypt wallet

### ISSUE THREAD

**Issue by lunokhod** [radix42/zcash-swing-wallet-ui#2]
I downloaded zcash4mac and everything seems to be working great, **except** that I can't seem to encrypt the wallet that contains the private keys. Is there a way to fix this? Is short, the "encrypt..." option is shown in the menu, but you can't click on it.

**Comment by radix42** [comment]
Its greyed out because the zcash core team is still working on re-enabling
wallet encryption....its disabled right now because the process of
encrypting/decrypting private keys for shielded z-addresses is going to
have to be wildly different than that from the bitcoin inherited
transparent t-addresses due to how it has to scan the blockchain
differently for them on startup.

As soon as its enabled, I'll be pushing an update that supports it.

**Comment by lunokhod** [comment]
I hope that this is their number one priority. No one would recommend having an unecrypted wallet on their computer... Thanks for the response.

**Comment by JayBrown** [comment]
Maybe you can create a workaround until wallet encryption is enabled. Create a growable read/write sparsebundle, encrypted either with a password or an S/MIME key, mount the volume, copy the wallet to the sparsebundle volume, move the original wallet file to a different location, then create a symbolic link to the wallet on the sparsebundle at the wallet's original location. So when you quit the Zcash app and stop zcashd, you can unmount the volume, and your wallet will be safe. Downside: when running zcashd and the zcash app, you need to mount the volume beforehand, and then it's not encrypted anymore, i.e. people with access to your system will have access to the wallet. (If it works, you can probably delete/shred the original wallet file.)

Afaik the Ledger Nano S now also supports Zcash, so that might be yet another alternative.
